name: HUGS
favicon: null
layout_spectrum: 0.48871
typography_spectrum: 0.56474
title: Hugs Grid Beta
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#004d00'
    - '#41a527'
    - '#f8fefe'
    - '#9bef1e'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
