name: HUGS
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4997
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4a176c'
    - '#f78e1f'
    - '#7582bf'
    - '#5fd1ea'
  brandStrength: 0.25
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
